blog/urls.py
from django.urls import path
# from .views import home, api
from .views import home, detail, category, author

app_name = 'blog'

urlpatterns = [
    
    path('', home, name='home'),
    path('page/<int:page_number>', home, name='home'),
    # path('api', api, name='api')
    # path('article/<slug:slug>', detail_article, name='detail_article')
    path('article/<slug:slug>', detail, name='detail'),
    path('category/<slug:slug>', category, name='category'),
    path('author/<slug:username>', author, name='author'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# Import your views if needed
# from blog.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home)
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

# Import Django settings and enable serving media files during development
from django.conf import settings
from django.conf.urls.static import static

# Serve media files from MEDIA_ROOT during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from account.models import User
from django.utils.html import format_html
from django.utils import timezone
from extensions.utils import jalali_conventor

from django.urls import reverse


# my manager
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')
    
class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


# Create your models here.

class Category(models.Model):
    
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیردسته')
    title = models.CharField(max_length=200, verbose_name= "عنوان دسته بندی")
    slug = models.SlugField(max_length=100, unique=True, verbose_name= "آدرس دسته بندی")
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود ؟")
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title
    
    objects = CategoryManager()



class Article(models.Model):
    STATUS_CHOICES = (

        ('d', 'پیش نویس'),
        ('p', 'منتشر شده')

    )

    # Fields for the Article model
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='articles', verbose_name="نویسنده")
    title = models.CharField(max_length=200, verbose_name= "عنوان مقاله")
    slug = models.SlugField(max_length=100, unique=True, verbose_name= "آدرس مقاله")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    description = models.TextField(verbose_name= "متن")
    thumbnail = models.ImageField(upload_to="images", verbose_name= "تصویر مقاله")
    publish = models.DateTimeField(default=timezone.now, verbose_name= "زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,default='d',null=True, blank=True, choices=STATUS_CHOICES, verbose_name= "وضعیت")

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقاله ها"
    
    
    # Methods for the Article model

    def __str__(self):
        return self.title
    
    def jpublish(self):

        return jalali_conventor(self.publish)
    
    jpublish.short_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)
    
    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px' src='{}'>".format(self.thumbnail.url))
    
    thumbnail_tag.short_description = "عکس"

    def category_to_str(self):
        # return "، ".join([category.title for category in obj.category.all()])
        return "، ".join([category.title for category in self.category_published()])    
    category_to_str.short_description = "دسته بندی"

    def get_absolute_url(self):
        return reverse("account:home")
    
    
    # Associate the custom manager with the Article model

    objects = ArticleManager()

blog/forms.py
# from django import forms
# from .models import Article

# # from account.mixins import FieldsMixin

# class ArticleAddForm(forms.ModelForm):
#    class Meta:
#        model = Article
#        fields = '__all__' # Include all fields from the model

from django import forms
from .models import Article

class ArticleAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # Extract the 'fields' argument from kwargs
        fields_arg = kwargs.pop('fields', None)

        # Call the parent class's __init__ method
        super().__init__(*args, **kwargs)

        # Update the 'fields' attribute based on the 'fields' argument
        if fields_arg:
            self.fields = {field_name: self.fields[field_name] for field_name in fields_arg}

    class Meta:
        model = Article
        fields = '__all__'  # Default fields option, can be overridden dynamically

blog/views.py
from django.core.paginator import Paginator
from account.models import User
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import Article, Category


# Create your views here.


# http test-------------------

# def home(request):
#     return HttpResponse("hello world")

# ----------------------------

# these are Json tests --------------------------------------


# def api(request):
#     return JsonResponse({"Title": "سلام دنیا"})

# def api(request):
#     data = {
#         "1": {
#             "title": "مقاله اول",
#             "id": 20,
#             "slug": "first article"
#         },

#         "2": {
#             "title": "مقاله دوم",
#             "id": 21,
#             "slug": "second article"
#         }

#     }
#     return JsonResponse(data)


#------------------------------------------------------------


# def home(request):

#     context = {
#         "articles":[
#             {
#             "username": "Amin",
#             "age": 24,
#             "job": "Programer",
#             "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1920px-Google_2015_logo.svg.png"
#             },
#             {
#             "username": "Alireza",
#             "age": 24,
#             "job": "Programer",
#             "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1920px-Google_2015_logo.svg.png"
#             },
#         ]
        
#     }

#     return render(request, "blog/home.html", context)





# Home view - paginated list of published articles
def home(request):

    articles_list = Article.objects.published()
    paginator = Paginator(articles_list, 3)  # Show 3 contacts per page.    
    page_number = request.GET.get("page_number")
    print()
    articles = paginator.get_page(page_number)
    for article in articles:
        print(article.title)
    context = {
        # "articles": Article.objects.all()
        # "articles": Article.objects.filter(status='p').order_by('-publish'), # [:2] #bracket shows number of articles that we want to show
        "articles": articles,
        "category": Category.objects.filter(status=True) # [:2] #bracket shows number of articles that we want to show

    }

    return render(request, "blog/home.html", context)

# Detail view for a specific article
def detail(request, slug):

    context = {
        # "articles": Article.objects.all()
        # "article": Article.objects.get(slug=slug)
        "article": get_object_or_404(Article, slug=slug, status="p"),
        "category": Category.objects.filter(status=True) # [:2] #bracket shows number of articles that we want to show
    }

    return render(request, "blog/detail.html", context)

# Category view - paginated list of articles in a specific category
def category(request, slug):
    
    category = get_object_or_404(Category, slug=slug, status=True)
    articles_list = category.articles.published()
    paginator = Paginator(articles_list, 3)  # Show 3 contacts per page.    
    page_number = request.GET.get("page_number")
    print()
    articles = paginator.get_page(page_number)
    for article in articles:
        print(article.title)
    context = {
        # "category": get_object_or_404(Category, slug=slug, status="True"),
        "category": category,
        "articles": articles
    }
    return render(request, "blog/category.html", context)

# Author view - paginated list of articles by a specific author
def author(request, username):
    author = get_object_or_404(User, username=username)
    articles = Article.objects.filter(author=author)
    paginator = Paginator(articles, 3) # Show 3 articles per page.
    page_number = request.GET.get("page_number")
    articles = paginator.get_page(page_number)
    context = {
        "author": author,
        "articles": articles
    }
    return render(request, "blog/author.html", context)

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/author.html
{% extends 'blog/base.html' %}

{% load static %}

{% block main %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>مقاله</h1>
                    <span class="subheading">سایتی برای اندیشمندان</span>
                </div>
            </div>
        </div>
    </div>
</header>

 
 <div class="container py-4">
   <h1 class="my-4">{{ author.username }}'s Articles</h1>
   {% for article in articles %}
     <div class="card my-4">
       <div class="card-body">
        <a href="{% url 'blog:detail' article.slug%}">
            <h2 class="post-title">{{article.title}}</h2>
            <h3 class="post-subtitle">{{article.description|truncatewords:30}}</h3>
        </a>         
        <p class="card-text">{{ article.descreption }}</p>
       </div>
     </div>
   {% endfor %}
   <div class="d-flex justify-content-center">
     {% if articles.has_previous %}
       <a href="?page_number={{ articles.previous_page_number }}" class="btn btn-primary me-2">Previous</a>
     {% endif %}
     {% if articles.has_next %}
       <a href="?page_number={{ articles.next_page_number }}" class="btn btn-primary">Next</a>
     {% endif %}
   </div>
 </div>


{% endblock %}

templates/blog/base.html
{% load static %}

{% load base_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>مقاله{% block title%}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />

        {% block custome-header%}

        {% endblock %}

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                
                {% category_navbar %}

            </div>
        </nav>
        
        
        
        {% block main %}

        {% endblock %}


        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/category.html
{% extends 'blog/base.html' %}

{% load static %}


{% block main %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>مقاله</h1>
                        <span class="subheading">سایتی برای اندیشمندان</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h3 class="alert alert-primary text-center" style="margin-bottom: 20px; font-size: 32px; font-weight: bold; background-color: #348; color: #fff; box-Shadow: 10px 10px 10px #00000080; border: none">دسته بندی: {{ category.title }}</h3>
                {#{% for article in category.articles %}#}
                {% for article in articles %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' article.slug%}">
                            <h2 class="post-title">{{article.title}}</h2>
                            <h3 class="post-subtitle">{{article.description|truncatewords:30}}</h3>
                        </a>
                        <p class="post-meta">

                            {{article.jpublish}}
                            نوشته شده توسط : 
                            <a href="{% url 'blog:author' article.author %}">{{article.author}}</a>
                            
                        </p>

                        <div>

                            {% for cat in article.category_published.all %}

                                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>

                            {% endfor %}

                        </div>

                    </div>
                <!-- Divider-->
                <hr class="my-4" />
                {% endfor %}
                
                <!-- Pager-->
                <!-- Mehran use this command to change the posision of older posts button -->
                <!-- <div class="clearfix pager-botton" >a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>-->
                <div class="row">
                    <div class="col-12 col-sm-6 ">
                        {% if articles.has_previous %}
                            <div class="d-flex justify-content-start mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:category' category.slug %}?page_number={{articles.previous_page_number}}">پست های جدید &rarr;</a></div> 
                        {% endif %}
                    </div>
                    <div class="col-12 col-sm-6">
                        {% if articles.has_next %}
                            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:category' category.slug %}?page_number={{articles.next_page_number}}">پست های قدیمی ←</a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/blog/detail.html
{% extends 'blog/base.html' %}

{% load static %}

{% block custome-header%}
<link rel="stylesheet" type="text/css" href="red.css">        
{% endblock %}

{% block title%} | {{article.title}}{% endblock %}

{% block main %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>{{article.title}}</h1>
                        <span class="subheading" style="margin-bottom: 20px; font-size: 24px; font-weight: bold;">The best information about {{article.title}}</span>
                        <time> {{article.jpublish}} </time>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7 text-justify" style = " text-align: justify !important; direction: ltr;">
                    {{article.description|safe|linebreaks}}

                    {% for cat in article.category_published.all %}

                        <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>

                    {% endfor %}

                    <p class="post-meta" dir="rtl"">
                        
                        {{article.jpublish}}
                        نویسنده : 
                        <a href="{% url 'blog:author' article.author %}">{{article.author}}</a>
                        {% comment %} {{article.jpublish}} {% endcomment %}
                        
                    </p>

                </div>
            </div>
        </div>
    </article>

    

{% endblock %}

templates/blog/detail_archive.html
<article>
    <img src="{{article.thumbnail.url}}" alt="{{article.title}}" width="400" height="400">
    <h1>{{ article.title }}</h1>
    <small>{{article.publish}}</small>
    <p class="article-description">Descreption: {{ article.description }}</p>
    <!-- You can add more details here -->
</article>

templates/blog/home.html
{% extends 'blog/base.html' %}

{% load static %}


{% block main %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>مقاله</h1>
                        <span class="subheading">سایتی برای اندیشمندان</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                
                {% for article in articles %}
                    <!-- Post preview-->
                    <div class="post-preview" style = " text-align: justify-all; text-align: left;" >
                        <a href="{% url 'blog:detail' article.slug%}">
                            <h2 class="post-title">{{article.title}}</h2>
                            <h3 class="post-subtitle">{{article.description|safe|truncatewords:30}}</h3>
                        </a>
                        <p class="post-meta">

                            {{article.jpublish}}
                            نوشته شده توسط : 
                            <a href="{% url 'blog:author' article.author %}">{{article.author}}</a>
                            
                        </p>

                        <div>

                            {% for cat in article.category_published.all %}

                                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>

                            {% endfor %}

                        </div>

                    </div>
                <!-- Divider-->
                <hr class="my-4" />
                {% endfor %}
                
                <!-- Pager-->
                <!-- Mehran use this command to change the posision of older posts button -->
                <!-- <div class="clearfix pager-botton" >a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>-->
                <div class="row">
                    <div class="col-12 col-sm-6 ">
                        {% if articles.has_previous %}
                            <div class="d-flex justify-content-start mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home' %}?page_number={{articles.previous_page_number}}">پست های جدید &rarr;</a></div> 
                        {% endif %}
                    </div>
                    <div class="col-12 col-sm-6">
                        {% if articles.has_next %}
                            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home' %}?page_number={{articles.next_page_number}}">پست های قدیمی ←</a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/blog/home_archive.html
{% comment %} this is html test {% endcomment %}
{% comment %} {{article.username}}
{%for article in articles%}

    <article>
        <h1>{{article.username}}</h1>
    </article>

{%endfor%} {% endcomment %}

{% comment %} <center>
    {% for article in articles %}
    <article>
        <h1>{{ article.id}}</h1>
        <h1>{{ article.username }}</h1>
        <p>Age: {{ article.age }}, Job: {{ article.job }}</p>
        <img src="{{article.img}}"
        <img src="{{article.thumbnail.url}}" alt="{{article.title}}" width="1000" height=1000>
        <!-- You can add more details here -->
    </article>
    {% endfor %}
</center> {% endcomment %}

<style>
    .article-description {
        margin-bottom: 5em; /* You can adjust the value according to your preference */
    }
</style>

<center>
    {% for article in articles %}
        <article>
            <img src="{{article.thumbnail.url}}" alt="{{article.title}}" width="400" height="400">
            <h1><a href="{% url 'blog:detail_article' article.slug %}">{{ article.title }}</a></h1> <!-- we can wright the path with hard coding like this: <a href="/article/{{article.slug}}">{{ article.title }}</a> -->
            <small>{{article.publish}}
            <p class="article-description">Descreption: {{ article.description }}</p>
            <!-- You can add more details here -->
        </article>
    {% endfor %}
</center>    